[package]
name = "fbdl-rs"
version = "0.1.0"
edition = "2021"
license = "GNU General Public License v3.0"
description = "Functional Bus Description Language"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
